### ISSUE TITLE
Белые пятная вместо космоса

### ISSUE THREAD

**Issue by KiPakr** [TauCetiStation/ColonialMarines_Redone#78]
В общем тут нечего объяснять. Бьенд не обновлялся.
https://prnt.sc/gsmtup

**Comment by P-20** [comment]
Не тот репозиторий, да и не по форме.

**Comment by KiPakr** [comment]
да я сам в ахуе как я сюда попал

**Comment by volas** [comment]
В любом случае, попробуй обновить бьенд, включить/выключить ускорение в его настройках, поставить/обновить DirectX. Возможно еще какие шаманства нужны, я уже плохо помню, но проблема частая была. И она не связанна с билдом, лучше обратиться сюда http://tauceti.ru/forums/index.php?board=86.0 (кто-то наверняка точнее подскажет)
